// ============================
// وضوح | Wuduh — Document Themes
// 125 ثيم لوني للمستندات — يُختار قبل التوليد
// ============================

export interface DocTheme {
  id: string;
  name: string;      // الاسم بالعربي
  nameEn: string;
  dark: string;      // خلفية الترويسة / اللون الداكن
  primary: string;   // اللون الأساسي
  accent: string;    // اللون المميز
  light: string;     // خلفية فاتحة
}

export const DOC_THEMES: DocTheme[] = [
  { id: "wuduh-classic", name: "وضوح الكلاسيكي", nameEn: "Wuduh Classic", dark: "#0F2057", primary: "#2563EB", accent: "#0EA5E9", light: "#F8FAFC" },
  { id: "graphite", name: "جرافيت", nameEn: "Graphite", dark: "#1F2937", primary: "#4B5563", accent: "#9CA3AF", light: "#F9FAFB" },
  { id: "slate", name: "إردوازي", nameEn: "Slate", dark: "#0F172A", primary: "#334155", accent: "#64748B", light: "#F8FAFC" },
  { id: "charcoal", name: "فحمي", nameEn: "Charcoal", dark: "#18181B", primary: "#3F3F46", accent: "#71717A", light: "#FAFAFA" },
  { id: "navy-gold", name: "كحلي وذهبي", nameEn: "Navy & Gold", dark: "#0B1E3F", primary: "#1E3A80", accent: "#D4A017", light: "#FBFAF5" },
  { id: "royal-blue-deep", name: "الأزرق الملكي غامق", nameEn: "Royal Blue Deep", dark: "#12233F", primary: "#1E57B8", accent: "#4964E9", light: "#F5F7FA" },
  { id: "royal-blue-vibrant", name: "الأزرق الملكي نابض", nameEn: "Royal Blue Vibrant", dark: "#132B53", primary: "#1363EC", accent: "#5A74F6", light: "#F5F7FA" },
  { id: "royal-blue-muted", name: "الأزرق الملكي هادئ", nameEn: "Royal Blue Muted", dark: "#24334C", primary: "#4167AA", accent: "#6E7ECF", light: "#F5F7FA" },
  { id: "royal-blue-night", name: "الأزرق الملكي ليلي", nameEn: "Royal Blue Night", dark: "#0C1A31", primary: "#1D4FA5", accent: "#3A55DF", light: "#F5F7FA" },
  { id: "sky-blue-deep", name: "أزرق سماوي غامق", nameEn: "Sky Blue Deep", dark: "#122D3F", primary: "#1E78B8", accent: "#4986E9", light: "#F5F8FA" },
  { id: "sky-blue-vibrant", name: "أزرق سماوي نابض", nameEn: "Sky Blue Vibrant", dark: "#133853", primary: "#1392EC", accent: "#5A96F6", light: "#F5F8FA" },
  { id: "sky-blue-muted", name: "أزرق سماوي هادئ", nameEn: "Sky Blue Muted", dark: "#243B4C", primary: "#417EAA", accent: "#6E93CF", light: "#F5F8FA" },
  { id: "sky-blue-night", name: "أزرق سماوي ليلي", nameEn: "Sky Blue Night", dark: "#0C2231", primary: "#1D6CA5", accent: "#3A79DF", light: "#F5F8FA" },
  { id: "teal-deep", name: "فيروزي غامق", nameEn: "Teal Deep", dark: "#12383F", primary: "#1E9FB8", accent: "#49AEE9", light: "#F5F9FA" },
  { id: "teal-vibrant", name: "فيروزي نابض", nameEn: "Teal Vibrant", dark: "#134853", primary: "#13C8EC", accent: "#5ABDF6", light: "#F5F9FA" },
  { id: "teal-muted", name: "فيروزي هادئ", nameEn: "Teal Muted", dark: "#24454C", primary: "#4198AA", accent: "#6EABCF", light: "#F5F9FA" },
  { id: "teal-night", name: "فيروزي ليلي", nameEn: "Teal Night", dark: "#0C2B31", primary: "#1D8EA5", accent: "#3AA2DF", light: "#F5F9FA" },
  { id: "sea-green-deep", name: "أخضر بحري غامق", nameEn: "Sea Green Deep", dark: "#123F38", primary: "#1EB89F", accent: "#49E3E9", light: "#F5FAF9" },
  { id: "sea-green-vibrant", name: "أخضر بحري نابض", nameEn: "Sea Green Vibrant", dark: "#135348", primary: "#13ECC8", accent: "#5AF1F6", light: "#F5FAF9" },
  { id: "sea-green-muted", name: "أخضر بحري هادئ", nameEn: "Sea Green Muted", dark: "#244C45", primary: "#41AA98", accent: "#6ECBCF", light: "#F5FAF9" },
  { id: "sea-green-night", name: "أخضر بحري ليلي", nameEn: "Sea Green Night", dark: "#0C312B", primary: "#1DA58E", accent: "#3AD9DF", light: "#F5FAF9" },
  { id: "emerald-deep", name: "زمردي غامق", nameEn: "Emerald Deep", dark: "#123F29", primary: "#1EB86B", accent: "#49E9B9", light: "#F5FAF7" },
  { id: "emerald-vibrant", name: "زمردي نابض", nameEn: "Emerald Vibrant", dark: "#135333", primary: "#13EC80", accent: "#5AF6C8", light: "#F5FAF7" },
  { id: "emerald-muted", name: "زمردي هادئ", nameEn: "Emerald Muted", dark: "#244C38", primary: "#41AA75", accent: "#6ECFB1", light: "#F5FAF7" },
  { id: "emerald-night", name: "زمردي ليلي", nameEn: "Emerald Night", dark: "#0C311F", primary: "#1DA561", accent: "#3ADFAD", light: "#F5FAF7" },
  { id: "forest-deep", name: "أخضر غابات غامق", nameEn: "Forest Deep", dark: "#123F1A", primary: "#1EB838", accent: "#49E984", light: "#F5FAF6" },
  { id: "forest-vibrant", name: "أخضر غابات نابض", nameEn: "Forest Vibrant", dark: "#13531E", primary: "#13EC37", accent: "#5AF693", light: "#F5FAF6" },
  { id: "forest-muted", name: "أخضر غابات هادئ", nameEn: "Forest Muted", dark: "#244C2B", primary: "#41AA52", accent: "#6ECF91", light: "#F5FAF6" },
  { id: "forest-night", name: "أخضر غابات ليلي", nameEn: "Forest Night", dark: "#0C3112", primary: "#1DA534", accent: "#3ADF76", light: "#F5FAF6" },
  { id: "olive-deep", name: "أخضر زيتوني غامق", nameEn: "Olive Deep", dark: "#253F12", primary: "#5EB81E", accent: "#6CE949", light: "#F7FAF5" },
  { id: "olive-vibrant", name: "أخضر زيتوني نابض", nameEn: "Olive Vibrant", dark: "#2E5313", primary: "#6DEC13", accent: "#7CF65A", light: "#F7FAF5" },
  { id: "olive-muted", name: "أخضر زيتوني هادئ", nameEn: "Olive Muted", dark: "#354C24", primary: "#6DAA41", accent: "#83CF6E", light: "#F7FAF5" },
  { id: "olive-night", name: "أخضر زيتوني ليلي", nameEn: "Olive Night", dark: "#1C310C", primary: "#56A51D", accent: "#5DDF3A", light: "#F7FAF5" },
  { id: "gold-deep", name: "ذهبي غامق", nameEn: "Gold Deep", dark: "#3F3C12", primary: "#B8AB1E", accent: "#D6E949", light: "#FAF9F5" },
  { id: "gold-vibrant", name: "ذهبي نابض", nameEn: "Gold Vibrant", dark: "#534D13", primary: "#ECDA13", accent: "#E4F65A", light: "#FAF9F5" },
  { id: "gold-muted", name: "ذهبي هادئ", nameEn: "Gold Muted", dark: "#4C4824", primary: "#AAA141", accent: "#C3CF6E", light: "#FAF9F5" },
  { id: "gold-night", name: "ذهبي ليلي", nameEn: "Gold Night", dark: "#312E0C", primary: "#A5991D", accent: "#CCDF3A", light: "#FAF9F5" },
  { id: "amber-deep", name: "كهرماني غامق", nameEn: "Amber Deep", dark: "#3F3012", primary: "#B8851E", accent: "#E9D349", light: "#FAF8F5" },
  { id: "amber-vibrant", name: "كهرماني نابض", nameEn: "Amber Vibrant", dark: "#533E13", primary: "#ECA413", accent: "#F6E25A", light: "#FAF8F5" },
  { id: "amber-muted", name: "كهرماني هادئ", nameEn: "Amber Muted", dark: "#4C3F24", primary: "#AA8741", accent: "#CFC26E", light: "#FAF8F5" },
  { id: "amber-night", name: "كهرماني ليلي", nameEn: "Amber Night", dark: "#31250C", primary: "#A5781D", accent: "#DFC93A", light: "#FAF8F5" },
  { id: "burnt-orange-deep", name: "برتقالي محروق غامق", nameEn: "Burnt Orange Deep", dark: "#3F2712", primary: "#B8661E", accent: "#E9B449", light: "#FAF7F5" },
  { id: "burnt-orange-vibrant", name: "برتقالي محروق نابض", nameEn: "Burnt Orange Vibrant", dark: "#533113", primary: "#EC7813", accent: "#F6C25A", light: "#FAF7F5" },
  { id: "burnt-orange-muted", name: "برتقالي محروق هادئ", nameEn: "Burnt Orange Muted", dark: "#4C3724", primary: "#AA7241", accent: "#CFAE6E", light: "#FAF7F5" },
  { id: "burnt-orange-night", name: "برتقالي محروق ليلي", nameEn: "Burnt Orange Night", dark: "#311D0C", primary: "#A55C1D", accent: "#DFA83A", light: "#FAF7F5" },
  { id: "terracotta-deep", name: "طوبي غامق", nameEn: "Terracotta Deep", dark: "#3F1E12", primary: "#B8471E", accent: "#E99449", light: "#FAF6F5" },
  { id: "terracotta-vibrant", name: "طوبي نابض", nameEn: "Terracotta Vibrant", dark: "#532413", primary: "#EC4D13", accent: "#F6A35A", light: "#FAF6F5" },
  { id: "terracotta-muted", name: "طوبي هادئ", nameEn: "Terracotta Muted", dark: "#4C2F24", primary: "#AA5D41", accent: "#CF9B6E", light: "#FAF6F5" },
  { id: "terracotta-night", name: "طوبي ليلي", nameEn: "Terracotta Night", dark: "#31160C", primary: "#A5411D", accent: "#DF873A", light: "#FAF6F5" },
  { id: "crimson-deep", name: "أحمر قرمزي غامق", nameEn: "Crimson Deep", dark: "#3F1612", primary: "#B82B1E", accent: "#E97749", light: "#FAF5F5" },
  { id: "crimson-vibrant", name: "أحمر قرمزي نابض", nameEn: "Crimson Vibrant", dark: "#531913", primary: "#EC2513", accent: "#F6865A", light: "#FAF5F5" },
  { id: "crimson-muted", name: "أحمر قرمزي هادئ", nameEn: "Crimson Muted", dark: "#4C2824", primary: "#AA4941", accent: "#CF896E", light: "#FAF5F5" },
  { id: "crimson-night", name: "أحمر قرمزي ليلي", nameEn: "Crimson Night", dark: "#310F0C", primary: "#A5281D", accent: "#DF683A", light: "#FAF5F5" },
  { id: "deep-rose-deep", name: "وردي عميق غامق", nameEn: "Deep Rose Deep", dark: "#3F121A", primary: "#B81E38", accent: "#E94F49", light: "#FAF5F6" },
  { id: "deep-rose-vibrant", name: "وردي عميق نابض", nameEn: "Deep Rose Vibrant", dark: "#53131E", primary: "#EC1337", accent: "#F65F5A", light: "#FAF5F6" },
  { id: "deep-rose-muted", name: "وردي عميق هادئ", nameEn: "Deep Rose Muted", dark: "#4C242B", primary: "#AA4152", accent: "#CF716E", light: "#FAF5F6" },
  { id: "deep-rose-night", name: "وردي عميق ليلي", nameEn: "Deep Rose Night", dark: "#310C12", primary: "#A51D34", accent: "#DF3F3A", light: "#FAF5F6" },
  { id: "berry-deep", name: "توتي غامق", nameEn: "Berry Deep", dark: "#3F1225", primary: "#B81E5E", accent: "#E9496C", light: "#FAF5F7" },
  { id: "berry-vibrant", name: "توتي نابض", nameEn: "Berry Vibrant", dark: "#53132E", primary: "#EC136D", accent: "#F65A7C", light: "#FAF5F7" },
  { id: "berry-muted", name: "توتي هادئ", nameEn: "Berry Muted", dark: "#4C2435", primary: "#AA416D", accent: "#CF6E83", light: "#FAF5F7" },
  { id: "berry-night", name: "توتي ليلي", nameEn: "Berry Night", dark: "#310C1C", primary: "#A51D56", accent: "#DF3A5D", light: "#FAF5F7" },
  { id: "fuchsia-deep", name: "فوشيا غامق", nameEn: "Fuchsia Deep", dark: "#3F1230", primary: "#B81E85", accent: "#E94994", light: "#FAF5F8" },
  { id: "fuchsia-vibrant", name: "فوشيا نابض", nameEn: "Fuchsia Vibrant", dark: "#53133E", primary: "#EC13A4", accent: "#F65AA3", light: "#FAF5F8" },
  { id: "fuchsia-muted", name: "فوشيا هادئ", nameEn: "Fuchsia Muted", dark: "#4C243F", primary: "#AA4187", accent: "#CF6E9B", light: "#FAF5F8" },
  { id: "fuchsia-night", name: "فوشيا ليلي", nameEn: "Fuchsia Night", dark: "#310C25", primary: "#A51D78", accent: "#DF3A87", light: "#FAF5F8" },
  { id: "purple-deep", name: "أرجواني غامق", nameEn: "Purple Deep", dark: "#3F123F", primary: "#B81EB8", accent: "#E949C9", light: "#FAF5FA" },
  { id: "purple-vibrant", name: "أرجواني نابض", nameEn: "Purple Vibrant", dark: "#531353", primary: "#EC13EC", accent: "#F65AD7", light: "#FAF5FA" },
  { id: "purple-muted", name: "أرجواني هادئ", nameEn: "Purple Muted", dark: "#4C244C", primary: "#AA41AA", accent: "#CF6EBB", light: "#FAF5FA" },
  { id: "purple-night", name: "أرجواني ليلي", nameEn: "Purple Night", dark: "#310C31", primary: "#A51DA5", accent: "#DF3ABE", light: "#FAF5FA" },
  { id: "violet-deep", name: "بنفسجي غامق", nameEn: "Violet Deep", dark: "#30123F", primary: "#851EB8", accent: "#D349E9", light: "#F8F5FA" },
  { id: "violet-vibrant", name: "بنفسجي نابض", nameEn: "Violet Vibrant", dark: "#3E1353", primary: "#A413EC", accent: "#E25AF6", light: "#F8F5FA" },
  { id: "violet-muted", name: "بنفسجي هادئ", nameEn: "Violet Muted", dark: "#3F244C", primary: "#8741AA", accent: "#C26ECF", light: "#F8F5FA" },
  { id: "violet-night", name: "بنفسجي ليلي", nameEn: "Violet Night", dark: "#250C31", primary: "#781DA5", accent: "#C93ADF", light: "#F8F5FA" },
  { id: "lavender-deep", name: "خزامي غامق", nameEn: "Lavender Deep", dark: "#23123F", primary: "#571EB8", accent: "#A449E9", light: "#F7F5FA" },
  { id: "lavender-vibrant", name: "خزامي نابض", nameEn: "Lavender Vibrant", dark: "#2B1353", primary: "#6313EC", accent: "#B35AF6", light: "#F7F5FA" },
  { id: "lavender-muted", name: "خزامي هادئ", nameEn: "Lavender Muted", dark: "#33244C", primary: "#6741AA", accent: "#A56ECF", light: "#F7F5FA" },
  { id: "lavender-night", name: "خزامي ليلي", nameEn: "Lavender Night", dark: "#1A0C31", primary: "#4F1DA5", accent: "#973ADF", light: "#F7F5FA" },
  { id: "indigo-deep", name: "نيلي غامق", nameEn: "Indigo Deep", dark: "#16123F", primary: "#2B1EB8", accent: "#7749E9", light: "#F5F5FA" },
  { id: "indigo-vibrant", name: "نيلي نابض", nameEn: "Indigo Vibrant", dark: "#191353", primary: "#2513EC", accent: "#865AF6", light: "#F5F5FA" },
  { id: "indigo-muted", name: "نيلي هادئ", nameEn: "Indigo Muted", dark: "#28244C", primary: "#4941AA", accent: "#896ECF", light: "#F5F5FA" },
  { id: "indigo-night", name: "نيلي ليلي", nameEn: "Indigo Night", dark: "#0F0C31", primary: "#281DA5", accent: "#683ADF", light: "#F5F5FA" },
  { id: "midnight-blue-deep", name: "أزرق ليلي غامق", nameEn: "Midnight Blue Deep", dark: "#121E3F", primary: "#1E45B8", accent: "#4951E9", light: "#F5F6FA" },
  { id: "midnight-blue-vibrant", name: "أزرق ليلي نابض", nameEn: "Midnight Blue Vibrant", dark: "#132353", primary: "#1349EC", accent: "#5A62F6", light: "#F5F6FA" },
  { id: "midnight-blue-muted", name: "أزرق ليلي هادئ", nameEn: "Midnight Blue Muted", dark: "#242E4C", primary: "#415BAA", accent: "#6E72CF", light: "#F5F6FA" },
  { id: "midnight-blue-night", name: "أزرق ليلي ليلي", nameEn: "Midnight Blue Night", dark: "#0C1531", primary: "#1D3FA5", accent: "#3A42DF", light: "#F5F6FA" },
  { id: "steel-deep", name: "فولاذي غامق", nameEn: "Steel Deep", dark: "#12293F", primary: "#1E6BB8", accent: "#4979E9", light: "#F5F7FA" },
  { id: "steel-vibrant", name: "فولاذي نابض", nameEn: "Steel Vibrant", dark: "#133353", primary: "#137FEC", accent: "#5A89F6", light: "#F5F7FA" },
  { id: "steel-muted", name: "فولاذي هادئ", nameEn: "Steel Muted", dark: "#24384C", primary: "#4175AA", accent: "#6E8BCF", light: "#F5F7FA" },
  { id: "steel-night", name: "فولاذي ليلي", nameEn: "Steel Night", dark: "#0C1F31", primary: "#1D61A5", accent: "#3A6BDF", light: "#F5F7FA" },
  { id: "petrol-deep", name: "أزرق بترولي غامق", nameEn: "Petrol Deep", dark: "#12303F", primary: "#1E85B8", accent: "#4994E9", light: "#F5F8FA" },
  { id: "petrol-vibrant", name: "أزرق بترولي نابض", nameEn: "Petrol Vibrant", dark: "#133E53", primary: "#13A4EC", accent: "#5AA3F6", light: "#F5F8FA" },
  { id: "petrol-muted", name: "أزرق بترولي هادئ", nameEn: "Petrol Muted", dark: "#243F4C", primary: "#4187AA", accent: "#6E9BCF", light: "#F5F8FA" },
  { id: "petrol-night", name: "أزرق بترولي ليلي", nameEn: "Petrol Night", dark: "#0C2531", primary: "#1D78A5", accent: "#3A87DF", light: "#F5F8FA" },
  { id: "dark-cyan-deep", name: "سماوي داكن غامق", nameEn: "Dark Cyan Deep", dark: "#123C3F", primary: "#1EABB8", accent: "#49BBE9", light: "#F5F9FA" },
  { id: "dark-cyan-vibrant", name: "سماوي داكن نابض", nameEn: "Dark Cyan Vibrant", dark: "#134D53", primary: "#13DAEC", accent: "#5ACAF6", light: "#F5F9FA" },
  { id: "dark-cyan-muted", name: "سماوي داكن هادئ", nameEn: "Dark Cyan Muted", dark: "#24484C", primary: "#41A1AA", accent: "#6EB3CF", light: "#F5F9FA" },
  { id: "dark-cyan-night", name: "سماوي داكن ليلي", nameEn: "Dark Cyan Night", dark: "#0C2E31", primary: "#1D99A5", accent: "#3AB0DF", light: "#F5F9FA" },
  { id: "mint-deep", name: "نعناعي غامق", nameEn: "Mint Deep", dark: "#123F2F", primary: "#1EB880", accent: "#49E9CE", light: "#F5FAF8" },
  { id: "mint-vibrant", name: "نعناعي نابض", nameEn: "Mint Vibrant", dark: "#13533B", primary: "#13EC9C", accent: "#5AF6DC", light: "#F5FAF8" },
  { id: "mint-muted", name: "نعناعي هادئ", nameEn: "Mint Muted", dark: "#244C3D", primary: "#41AA83", accent: "#6ECFBE", light: "#F5FAF8" },
  { id: "mint-night", name: "نعناعي ليلي", nameEn: "Mint Night", dark: "#0C3123", primary: "#1DA573", accent: "#3ADFC3", light: "#F5FAF8" },
  { id: "lime-deep", name: "ليموني غامق", nameEn: "Lime Deep", dark: "#1A3F12", primary: "#38B81E", accent: "#49E94F", light: "#F6FAF5" },
  { id: "lime-vibrant", name: "ليموني نابض", nameEn: "Lime Vibrant", dark: "#1E5313", primary: "#37EC13", accent: "#5AF65F", light: "#F6FAF5" },
  { id: "lime-muted", name: "ليموني هادئ", nameEn: "Lime Muted", dark: "#2B4C24", primary: "#52AA41", accent: "#6ECF71", light: "#F6FAF5" },
  { id: "lime-night", name: "ليموني ليلي", nameEn: "Lime Night", dark: "#12310C", primary: "#34A51D", accent: "#3ADF3F", light: "#F6FAF5" },
  { id: "mustard-deep", name: "خردلي غامق", nameEn: "Mustard Deep", dark: "#3F3412", primary: "#B8921E", accent: "#E9E149", light: "#FAF8F5" },
  { id: "mustard-vibrant", name: "خردلي نابض", nameEn: "Mustard Vibrant", dark: "#534313", primary: "#ECB613", accent: "#F6EF5A", light: "#FAF8F5" },
  { id: "mustard-muted", name: "خردلي هادئ", nameEn: "Mustard Muted", dark: "#4C4224", primary: "#AA9041", accent: "#CFCA6E", light: "#FAF8F5" },
  { id: "mustard-night", name: "خردلي ليلي", nameEn: "Mustard Night", dark: "#31280C", primary: "#A5831D", accent: "#DFD73A", light: "#FAF8F5" },
  { id: "copper-deep", name: "نحاسي غامق", nameEn: "Copper Deep", dark: "#3F2112", primary: "#B8511E", accent: "#E99E49", light: "#FAF7F5" },
  { id: "copper-vibrant", name: "نحاسي نابض", nameEn: "Copper Vibrant", dark: "#532813", primary: "#EC5B13", accent: "#F6AE5A", light: "#FAF7F5" },
  { id: "copper-muted", name: "نحاسي هادئ", nameEn: "Copper Muted", dark: "#4C3224", primary: "#AA6441", accent: "#CFA16E", light: "#FAF7F5" },
  { id: "copper-night", name: "نحاسي ليلي", nameEn: "Copper Night", dark: "#31180C", primary: "#A54A1D", accent: "#DF923A", light: "#FAF7F5" },
  { id: "rust-deep", name: "صدئي غامق", nameEn: "Rust Deep", dark: "#3F1A12", primary: "#B8381E", accent: "#E98449", light: "#FAF6F5" },
  { id: "rust-vibrant", name: "صدئي نابض", nameEn: "Rust Vibrant", dark: "#531E13", primary: "#EC3713", accent: "#F6935A", light: "#FAF6F5" },
  { id: "rust-muted", name: "صدئي هادئ", nameEn: "Rust Muted", dark: "#4C2B24", primary: "#AA5241", accent: "#CF916E", light: "#FAF6F5" },
  { id: "rust-night", name: "صدئي ليلي", nameEn: "Rust Night", dark: "#31120C", primary: "#A5341D", accent: "#DF763A", light: "#FAF6F5" },
  { id: "maroon-deep", name: "عنابي غامق", nameEn: "Maroon Deep", dark: "#3F121E", primary: "#B81E45", accent: "#E94951", light: "#FAF5F6" },
  { id: "maroon-vibrant", name: "عنابي نابض", nameEn: "Maroon Vibrant", dark: "#531323", primary: "#EC1349", accent: "#F65A62", light: "#FAF5F6" },
  { id: "maroon-muted", name: "عنابي هادئ", nameEn: "Maroon Muted", dark: "#4C242E", primary: "#AA415B", accent: "#CF6E72", light: "#FAF5F6" },
  { id: "maroon-night", name: "عنابي ليلي", nameEn: "Maroon Night", dark: "#310C15", primary: "#A51D3F", accent: "#DF3A42", light: "#FAF5F6" },
  { id: "royal-violet-deep", name: "بنفسجي ملكي غامق", nameEn: "Royal Violet Deep", dark: "#1E123F", primary: "#451EB8", accent: "#9149E9", light: "#F6F5FA" },
  { id: "royal-violet-vibrant", name: "بنفسجي ملكي نابض", nameEn: "Royal Violet Vibrant", dark: "#231353", primary: "#4913EC", accent: "#A05AF6", light: "#F6F5FA" },
  { id: "royal-violet-muted", name: "بنفسجي ملكي هادئ", nameEn: "Royal Violet Muted", dark: "#2E244C", primary: "#5B41AA", accent: "#996ECF", light: "#F6F5FA" },
  { id: "royal-violet-night", name: "بنفسجي ملكي ليلي", nameEn: "Royal Violet Night", dark: "#150C31", primary: "#3F1DA5", accent: "#843ADF", light: "#F6F5FA" },
];

export const DEFAULT_THEME_ID = "wuduh-classic";

export function getTheme(id?: string | null): DocTheme {
  return DOC_THEMES.find(t => t.id === id) ?? DOC_THEMES[0];
}

// Convert #RRGGBB → [r,g,b] for jsPDF
export function hexToRgb(hex: string): [number, number, number] {
  const h = hex.replace('#', '');
  return [parseInt(h.slice(0,2),16), parseInt(h.slice(2,4),16), parseInt(h.slice(4,6),16)];
}
