// ============================
// وضوح | Wuduh — DOCX Generator
// يولّد ملفات Word احترافية من بيانات AI
// ============================

import {
  Document, Packer, Paragraph, Table, TableRow, TableCell,
  TextRun, HeadingLevel, AlignmentType, WidthType, BorderStyle,
  ShadingType, Header, Footer,
  TableLayoutType, VerticalAlign, PageBreak,
  convertInchesToTwip,
} from "docx";

// Brand colors as hex
const NAVY    = "0F2057";
const PRIMARY = "2563EB";
const ACCENT  = "0EA5E9";
const GOLD    = "F59E0B";
const SUCCESS = "10B981";
const BG_LIGHT = "F8FAFC";
const BORDER  = "E2E8F0";
const TEXT    = "0F172A";
const TEXT_MID = "334155";
const TEXT_LIGHT = "64748B";
const WHITE   = "FFFFFF";

// ============================
// Helpers
// ============================
function headerParagraph(text: string): Paragraph {
  return new Paragraph({
    children: [
      new TextRun({ text: "Wuduh | وضوح  •  PMI/PMBOK Guide 7th Edition", size: 16, color: TEXT_LIGHT }),
      new TextRun({ text: `\t${text}`, size: 16, color: TEXT_LIGHT }),
    ],
    alignment: AlignmentType.LEFT,
    tabStops: [{ type: "right", position: convertInchesToTwip(6.5) }],
  });
}

function footerParagraph(): Paragraph {
  return new Paragraph({
    children: [
      new TextRun({ text: `Generated by Wuduh AI  •  `, size: 16, color: TEXT_LIGHT }),
      new TextRun({ text: new Date().toLocaleDateString("en-GB"), size: 16, color: TEXT_LIGHT }),
      new TextRun({ text: "\t", size: 16 }),
      new TextRun({ text: new Date().getFullYear().toString(), size: 16, color: TEXT_LIGHT }),
    ],
    alignment: AlignmentType.LEFT,
    tabStops: [{ type: "right", position: convertInchesToTwip(6.5) }],
  });
}

function coverTitle(text: string): Paragraph {
  return new Paragraph({
    heading: HeadingLevel.TITLE,
    alignment: AlignmentType.CENTER,
    children: [new TextRun({ text, size: 56, bold: true, color: WHITE })],
  });
}

function sectionHeading(text: string): Paragraph {
  return new Paragraph({
    heading: HeadingLevel.HEADING_1,
    children: [new TextRun({ text, size: 28, bold: true, color: PRIMARY })],
    spacing: { before: 400, after: 120 },
    border: { bottom: { color: ACCENT, size: 8, style: BorderStyle.SINGLE, space: 4 } },
  });
}

function subHeading(text: string): Paragraph {
  return new Paragraph({
    heading: HeadingLevel.HEADING_2,
    children: [new TextRun({ text, size: 22, bold: true, color: NAVY })],
    spacing: { before: 300, after: 80 },
  });
}

function bodyText(text: string): Paragraph {
  return new Paragraph({
    children: [new TextRun({ text, size: 20, color: TEXT_MID })],
    spacing: { after: 100 },
  });
}

function bulletItem(text: string): Paragraph {
  return new Paragraph({
    children: [new TextRun({ text, size: 20, color: TEXT_MID })],
    bullet: { level: 0 },
    spacing: { after: 60 },
  });
}

function infoRow(label: string, value: string): TableRow {
  return new TableRow({
    children: [
      new TableCell({
        children: [new Paragraph({ children: [new TextRun({ text: label, size: 18, bold: true, color: NAVY })] })],
        shading: { fill: "EFF6FF", type: ShadingType.CLEAR, color: "auto" },
        width: { size: 30, type: WidthType.PERCENTAGE },
        verticalAlign: VerticalAlign.CENTER,
        margins: { top: 80, bottom: 80, left: 120, right: 80 },
      }),
      new TableCell({
        children: [new Paragraph({ children: [new TextRun({ text: value, size: 18, color: TEXT })] })],
        width: { size: 70, type: WidthType.PERCENTAGE },
        verticalAlign: VerticalAlign.CENTER,
        margins: { top: 80, bottom: 80, left: 120, right: 80 },
      }),
    ],
  });
}

function makeTable(headers: string[], rows: string[][]): Table {
  return new Table({
    width: { size: 100, type: WidthType.PERCENTAGE },
    layout: TableLayoutType.FIXED,
    rows: [
      new TableRow({
        tableHeader: true,
        children: headers.map(h =>
          new TableCell({
            children: [new Paragraph({ children: [new TextRun({ text: h, size: 18, bold: true, color: WHITE })] })],
            shading: { fill: NAVY, type: ShadingType.CLEAR, color: "auto" },
            margins: { top: 80, bottom: 80, left: 100, right: 60 },
          })
        ),
      }),
      ...rows.map((row, rowIdx) =>
        new TableRow({
          children: row.map(cell =>
            new TableCell({
              children: [new Paragraph({ children: [new TextRun({ text: cell || "—", size: 17, color: TEXT })] })],
              shading: { fill: rowIdx % 2 === 0 ? "FFFFFF" : BG_LIGHT, type: ShadingType.CLEAR, color: "auto" },
              margins: { top: 70, bottom: 70, left: 100, right: 60 },
            })
          ),
        })
      ),
    ],
  });
}

// ============================
// 1. Project Charter DOCX
// ============================
export async function generateCharterDOCX(data: Record<string, unknown>, projectName: string): Promise<Uint8Array> {
  const children: (Paragraph | Table)[] = [
    // Cover page section (simulated with styling)
    new Paragraph({
      children: [new TextRun({ text: "Wuduh | وضوح", size: 64, bold: true, color: PRIMARY })],
      alignment: AlignmentType.CENTER,
      spacing: { before: 1440, after: 200 },
    }),
    new Paragraph({
      children: [new TextRun({ text: "PROJECT CHARTER", size: 52, bold: true, color: NAVY })],
      alignment: AlignmentType.CENTER,
      spacing: { after: 100 },
    }),
    new Paragraph({
      children: [new TextRun({ text: projectName, size: 36, color: TEXT_MID })],
      alignment: AlignmentType.CENTER,
      spacing: { after: 400 },
    }),
    new Paragraph({
      children: [new TextRun({ text: "PMI/PMBOK Guide 7th Edition Compliant", size: 20, color: ACCENT, italics: true })],
      alignment: AlignmentType.CENTER,
      spacing: { after: 800 },
    }),
    new Paragraph({ children: [new PageBreak()] }),

    // Document info table
    sectionHeading("1. Document Information"),
  ];

  const infoTable = new Table({
    width: { size: 100, type: WidthType.PERCENTAGE },
    rows: [
      infoRow("Project Name", (data.project_name as string) || projectName),
      infoRow("Document Number", (data.project_number as string) || "WUD-001"),
      infoRow("Version", (data.version as string) || "1.0"),
      infoRow("Preparation Date", (data.preparation_date as string) || new Date().toISOString().split("T")[0]),
      infoRow("Prepared By", (data.project_manager as string) || "Project Manager"),
    ],
  });
  children.push(infoTable);

  // Purpose
  children.push(sectionHeading("2. Project Purpose"));
  children.push(bodyText((data.purpose as string) || ""));

  // Description
  children.push(sectionHeading("3. Project Description"));
  children.push(bodyText((data.description as string) || ""));

  // Objectives
  children.push(sectionHeading("4. Project Objectives"));
  const objectives = (data.objectives as string[]) || [];
  objectives.forEach(obj => children.push(bulletItem(obj)));

  // Scope
  children.push(sectionHeading("5. Project Scope"));
  children.push(subHeading("5.1 Included in Scope"));
  ((data.scope_included as string[]) || []).forEach(s => children.push(bulletItem(s)));
  children.push(subHeading("5.2 Excluded from Scope"));
  ((data.scope_excluded as string[]) || []).forEach(s => children.push(bulletItem(s)));

  // Stakeholders
  children.push(sectionHeading("6. Key Stakeholders"));
  const stakeholders = (data.stakeholders as Array<{name:string;role:string;influence:string;interest:string}>) || [];
  if (stakeholders.length > 0) {
    children.push(makeTable(
      ["Name/Org", "Role", "Influence", "Interest"],
      stakeholders.map(s => [s.name, s.role, s.influence, s.interest])
    ));
  }

  // Budget
  children.push(sectionHeading("7. Budget Summary"));
  const budget = (data.budget_summary as {total:number;currency:string;notes:string}) || {};
  children.push(makeTable(
    ["Total Budget", "Currency", "Notes"],
    [[String(budget.total || 0), budget.currency || "SAR", budget.notes || ""]]
  ));

  // Assumptions
  children.push(sectionHeading("8. Assumptions & Constraints"));
  children.push(subHeading("8.1 Assumptions"));
  ((data.assumptions as string[]) || []).forEach(a => children.push(bulletItem(a)));
  children.push(subHeading("8.2 Constraints"));
  ((data.constraints as string[]) || []).forEach(c => children.push(bulletItem(c)));

  // Risks
  children.push(sectionHeading("9. High-Level Risks"));
  ((data.risks_summary as string[]) || []).forEach(r => children.push(bulletItem(r)));

  // Success Criteria
  children.push(sectionHeading("10. Success Criteria"));
  ((data.success_criteria as string[]) || []).forEach(c => children.push(bulletItem(c)));

  // Authorization
  children.push(sectionHeading("11. Authorization"));
  const authTable = new Table({
    width: { size: 100, type: WidthType.PERCENTAGE },
    rows: [
      new TableRow({
        children: [
          new TableCell({
            children: [
              new Paragraph({ children: [new TextRun({ text: "Project Sponsor", size: 18, bold: true, color: NAVY })] }),
              new Paragraph({ children: [new TextRun({ text: "Name: ________________________", size: 18, color: TEXT_MID })] }),
              new Paragraph({ children: [new TextRun({ text: "Signature: ____________________", size: 18, color: TEXT_MID })] }),
              new Paragraph({ children: [new TextRun({ text: "Date: _________________________", size: 18, color: TEXT_MID })] }),
            ],
            margins: { top: 160, bottom: 160, left: 200, right: 200 },
          }),
          new TableCell({
            children: [
              new Paragraph({ children: [new TextRun({ text: "Project Manager", size: 18, bold: true, color: NAVY })] }),
              new Paragraph({ children: [new TextRun({ text: "Name: ________________________", size: 18, color: TEXT_MID })] }),
              new Paragraph({ children: [new TextRun({ text: "Signature: ____________________", size: 18, color: TEXT_MID })] }),
              new Paragraph({ children: [new TextRun({ text: "Date: _________________________", size: 18, color: TEXT_MID })] }),
            ],
            margins: { top: 160, bottom: 160, left: 200, right: 200 },
          }),
        ],
      }),
    ],
  });
  children.push(authTable);

  const doc = new Document({
    styles: {
      default: {
        document: {
          run: { font: "Calibri", size: 20, color: TEXT },
          paragraph: { spacing: { line: 276 } },
        },
      },
    },
    sections: [{
      headers: { default: new Header({ children: [headerParagraph("Project Charter")] }) },
      footers: { default: new Footer({ children: [footerParagraph()] }) },
      children,
    }],
  });

  return Packer.toBuffer(doc) as unknown as Promise<Uint8Array>;
}

// ============================
// 2. Project Management Plan DOCX
// ============================
export async function generateProjectPlanDOCX(agendaData: Record<string, unknown>, projectName: string): Promise<Uint8Array> {
  const children: (Paragraph | Table)[] = [
    // Cover
    new Paragraph({
      children: [new TextRun({ text: "PROJECT MANAGEMENT PLAN", size: 52, bold: true, color: NAVY })],
      alignment: AlignmentType.CENTER,
      spacing: { before: 1440, after: 200 },
    }),
    new Paragraph({
      children: [new TextRun({ text: projectName, size: 36, color: TEXT_MID })],
      alignment: AlignmentType.CENTER,
      spacing: { after: 400 },
    }),
    new Paragraph({ children: [new PageBreak()] }),

    sectionHeading("1. Project Overview"),
    bodyText((agendaData.project_overview as string) || ""),

    sectionHeading("2. Methodology"),
    makeTable(
      ["Methodology", "Estimated Effort", "Duration", "Team Size"],
      [[
        String(agendaData.methodology || "Predictive"),
        `${agendaData.estimated_effort_hours || 0} hrs`,
        `${agendaData.duration_weeks || 0} weeks`,
        `${agendaData.team_size_recommended || 0} members`,
      ]]
    ),

    sectionHeading("3. Project Phases"),
  ];

  const phases = (agendaData.phases as Array<{name:string;start_week:number;end_week:number;description:string;deliverables:string[]}>) || [];
  if (phases.length > 0) {
    children.push(makeTable(
      ["Phase", "Start Week", "End Week", "Description", "Key Deliverables"],
      phases.map(p => [p.name, `Wk ${p.start_week}`, `Wk ${p.end_week}`, p.description, (p.deliverables || []).join(", ")])
    ));
  }

  children.push(sectionHeading("4. Key Milestones"));
  const milestones = (agendaData.key_milestones as Array<{name:string;week:number;description:string;success_criteria:string}>) || [];
  if (milestones.length > 0) {
    children.push(makeTable(
      ["Milestone", "Week", "Description", "Success Criteria"],
      milestones.map(m => [m.name, `Wk ${m.week}`, m.description, m.success_criteria])
    ));
  }

  children.push(sectionHeading("5. Key Performance Indicators"));
  const kpis = (agendaData.kpis as Array<{name:string;target:string;measurement_method:string;frequency:string}>) || [];
  if (kpis.length > 0) {
    children.push(makeTable(
      ["KPI", "Target", "Measurement Method", "Frequency"],
      kpis.map(k => [k.name, k.target, k.measurement_method, k.frequency])
    ));
  }

  children.push(sectionHeading("6. Critical Success Factors"));
  ((agendaData.critical_success_factors as string[]) || []).forEach(f => children.push(bulletItem(f)));

  children.push(sectionHeading("7. Recommendations"));
  ((agendaData.recommendations as string[]) || []).forEach(r => children.push(bulletItem(r)));

  const doc = new Document({
    sections: [{
      headers: { default: new Header({ children: [headerParagraph("Project Management Plan")] }) },
      footers: { default: new Footer({ children: [footerParagraph()] }) },
      children,
    }],
  });

  return Packer.toBuffer(doc) as unknown as Promise<Uint8Array>;
}

// ============================
// 3. Risk Register DOCX
// ============================
export async function generateRiskRegisterDOCX(data: Record<string, unknown>, projectName: string): Promise<Uint8Array> {
  const children: (Paragraph | Table)[] = [
    new Paragraph({
      children: [new TextRun({ text: "RISK REGISTER", size: 52, bold: true, color: NAVY })],
      alignment: AlignmentType.CENTER,
      spacing: { before: 1440, after: 200 },
    }),
    new Paragraph({
      children: [new TextRun({ text: projectName, size: 36, color: TEXT_MID })],
      alignment: AlignmentType.CENTER,
      spacing: { after: 800 },
    }),
    new Paragraph({ children: [new PageBreak()] }),

    sectionHeading("1. Risk Summary"),
  ];

  const summary = (data.summary as {total_risks:number;critical:number;high:number;medium:number;low:number;overall_risk_level:string}) || {};
  children.push(makeTable(
    ["Total Risks", "Critical", "High", "Medium", "Low", "Overall Level"],
    [[
      String(summary.total_risks || 0),
      String(summary.critical || 0),
      String(summary.high || 0),
      String(summary.medium || 0),
      String(summary.low || 0),
      summary.overall_risk_level || "Medium",
    ]]
  ));

  children.push(sectionHeading("2. Risk Register"));
  const risks = (data.risks as Array<{
    id:string; risk_statement:string; category:string;
    probability_score:number; impact_score:number; risk_score:number;
    risk_level:string; response_strategy:string; contingency_plan:string; owner:string; status:string;
  }>) || [];

  if (risks.length > 0) {
    children.push(makeTable(
      ["ID", "Risk Statement", "Category", "P", "I", "Score", "Level", "Strategy", "Owner"],
      risks.map(r => [r.id, r.risk_statement, r.category, String(r.probability_score), String(r.impact_score), String(r.risk_score), r.risk_level, r.response_strategy, r.owner])
    ));
  }

  children.push(sectionHeading("3. Risk Response Details"));
  risks.forEach(r => {
    children.push(subHeading(`${r.id}: ${r.risk_statement.substring(0, 60)}`));
    children.push(makeTable(
      ["Field", "Details"],
      [
        ["Response Strategy", r.response_strategy],
        ["Contingency Plan", r.contingency_plan],
        ["Owner", r.owner],
        ["Status", r.status],
      ]
    ));
  });

  const doc = new Document({
    sections: [{
      headers: { default: new Header({ children: [headerParagraph("Risk Register")] }) },
      footers: { default: new Footer({ children: [footerParagraph()] }) },
      children,
    }],
  });

  return Packer.toBuffer(doc) as unknown as Promise<Uint8Array>;
}
