// ============================
// وضوح | Wuduh — PDF Generator
// يولّد ملفات PDF احترافية من بيانات AI
// ============================

import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

// ألوان الهوية
const COLORS = {
  navyDark:  [15,  32,  87],
  navy:      [30,  58, 138],
  primary:   [37,  99, 235],
  accent:    [14, 165, 233],
  gold:      [245,158, 11],
  success:   [16, 185, 129],
  text:      [15,  23,  42],
  textMid:   [51,  65,  85],
  textLight: [100,116, 139],
  bgLight:   [248,250,252],
  border:    [226,232,240],
  white:     [255,255,255],
};

function createBasePDF(): jsPDF {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  doc.setLanguage("ar");
  return doc;
}

function addHeader(doc: jsPDF, title: string, subtitle?: string, pageNum = 1) {
  const W = doc.internal.pageSize.getWidth();

  // Gradient header background
  doc.setFillColor(...COLORS.navyDark as [number,number,number]);
  doc.rect(0, 0, W, 35, "F");

  // Logo mark
  doc.setFillColor(...COLORS.accent as [number,number,number]);
  doc.roundedRect(10, 7, 20, 20, 3, 3, "F");
  doc.setTextColor(...COLORS.white as [number,number,number]);
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("W", 20, 20, { align: "center" });

  // Brand name
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(255, 255, 255);
  doc.text("Wuduh | وضوح", 35, 14);
  doc.setFontSize(7);
  doc.setTextColor(180, 200, 240);
  doc.text("PMI/PMBOK Certified AI Platform", 35, 20);

  // Title (right aligned for Arabic context)
  doc.setFontSize(13);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...COLORS.white as [number,number,number]);
  doc.text(title, W - 15, 16, { align: "right" });

  if (subtitle) {
    doc.setFontSize(8);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(180, 200, 240);
    doc.text(subtitle, W - 15, 24, { align: "right" });
  }

  // Page number
  doc.setFontSize(7);
  doc.setTextColor(150, 170, 210);
  doc.text(`Page ${pageNum}`, W - 10, 32, { align: "right" });
}

function addFooter(doc: jsPDF) {
  const W = doc.internal.pageSize.getWidth();
  const H = doc.internal.pageSize.getHeight();

  doc.setFillColor(...COLORS.bgLight as [number,number,number]);
  doc.rect(0, H - 12, W, 12, "F");
  doc.setDrawColor(...COLORS.border as [number,number,number]);
  doc.line(0, H - 12, W, H - 12);

  doc.setFontSize(7);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(...COLORS.textLight as [number,number,number]);
  doc.text("Generated by Wuduh AI | وضوح — PMI/PMBOK Guide 7th Edition", 15, H - 5);
  doc.text(new Date().toLocaleDateString("ar-SA"), W - 15, H - 5, { align: "right" });
}

function addSectionTitle(doc: jsPDF, title: string, y: number): number {
  const W = doc.internal.pageSize.getWidth();
  doc.setFillColor(...COLORS.primary as [number,number,number]);
  doc.rect(15, y, 3, 7, "F");
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...COLORS.navy as [number,number,number]);
  doc.text(title, 22, y + 5.5);
  return y + 14;
}

function addInfoBox(doc: jsPDF, label: string, value: string, x: number, y: number, w: number, h: number) {
  doc.setFillColor(...COLORS.bgLight as [number,number,number]);
  doc.setDrawColor(...COLORS.border as [number,number,number]);
  doc.roundedRect(x, y, w, h, 2, 2, "FD");

  doc.setFontSize(7);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(...COLORS.textLight as [number,number,number]);
  doc.text(label, x + 4, y + 5);

  doc.setFontSize(9);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...COLORS.text as [number,number,number]);
  doc.text(value, x + 4, y + 11);
}

// ============================
// 1. Project Charter PDF
// ============================
export async function generateCharterPDF(data: Record<string, unknown>, projectName: string): Promise<Uint8Array> {
  const doc = createBasePDF();
  const W = doc.internal.pageSize.getWidth();
  let y = 45;

  addHeader(doc, "Project Charter", `ميثاق المشروع — ${projectName}`);
  addFooter(doc);

  // Project info boxes
  const boxes = [
    { label: "Project Name", value: (data.project_name as string) || projectName },
    { label: "Document No.", value: (data.project_number as string) || "WUD-001" },
    { label: "Version", value: (data.version as string) || "1.0" },
    { label: "Date", value: (data.preparation_date as string) || new Date().toISOString().split("T")[0] },
  ];

  const boxW = (W - 30) / 4;
  boxes.forEach((box, i) => addInfoBox(doc, box.label, box.value, 15 + i * (boxW + 2), y, boxW, 18));
  y += 28;

  // Purpose
  y = addSectionTitle(doc, "1. Purpose & Description", y);
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(...COLORS.textMid as [number,number,number]);
  const purposeLines = doc.splitTextToSize((data.purpose as string) || "", W - 30);
  doc.text(purposeLines, 15, y);
  y += purposeLines.length * 5 + 5;

  const descLines = doc.splitTextToSize((data.description as string) || "", W - 30);
  doc.text(descLines, 15, y);
  y += descLines.length * 5 + 8;

  // Objectives
  y = addSectionTitle(doc, "2. Objectives", y);
  const objectives = (data.objectives as string[]) || [];
  objectives.forEach((obj, i) => {
    doc.setFillColor(...COLORS.accent as [number,number,number]);
    doc.circle(18, y + 1.5, 1.5, "F");
    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(...COLORS.textMid as [number,number,number]);
    const lines = doc.splitTextToSize(`${i + 1}. ${obj}`, W - 35);
    doc.text(lines, 22, y + 3);
    y += lines.length * 5 + 3;
  });
  y += 5;

  // Scope table
  y = addSectionTitle(doc, "3. Scope", y);
  autoTable(doc, {
    startY: y,
    head: [["In Scope", "Out of Scope"]],
    body: [[(data.scope_included as string[] || []).join("\n"), (data.scope_excluded as string[] || []).join("\n")]],
    styles: { font: "helvetica", fontSize: 8, cellPadding: 3 },
    headStyles: { fillColor: COLORS.navy as [number,number,number], textColor: 255, fontStyle: "bold" },
    columnStyles: { 0: { cellWidth: (W - 30) / 2 }, 1: { cellWidth: (W - 30) / 2 } },
    margin: { left: 15, right: 15 },
  });
  y = (doc as any).lastAutoTable.finalY + 10;

  // Stakeholders
  if (y > 220) { doc.addPage(); addHeader(doc, "Project Charter", `ميثاق المشروع — ${projectName}`, 2); addFooter(doc); y = 45; }
  y = addSectionTitle(doc, "4. Key Stakeholders", y);
  const stakeholders = (data.stakeholders as Array<{name:string; role:string; influence:string; interest:string}>) || [];
  if (stakeholders.length > 0) {
    autoTable(doc, {
      startY: y,
      head: [["Name/Role", "Role", "Influence", "Interest"]],
      body: stakeholders.map(s => [s.name, s.role, s.influence, s.interest]),
      styles: { font: "helvetica", fontSize: 8, cellPadding: 3 },
      headStyles: { fillColor: COLORS.navy as [number,number,number], textColor: 255, fontStyle: "bold" },
      alternateRowStyles: { fillColor: COLORS.bgLight as [number,number,number] },
      margin: { left: 15, right: 15 },
    });
    y = (doc as any).lastAutoTable.finalY + 10;
  }

  // Budget
  if (data.budget_summary) {
    y = addSectionTitle(doc, "5. Budget Summary", y);
    const budget = data.budget_summary as { total: number; currency: string; notes: string };
    addInfoBox(doc, "Total Budget", `${budget.total?.toLocaleString()} ${budget.currency}`, 15, y, 80, 18);
    if (budget.notes) {
      doc.setFontSize(8); doc.setFont("helvetica", "normal"); doc.setTextColor(...COLORS.textMid as [number,number,number]);
      doc.text(budget.notes, 100, y + 9);
    }
    y += 28;
  }

  // Risks
  if (y > 220) { doc.addPage(); addHeader(doc, "Project Charter", `ميثاق المشروع — ${projectName}`, 3); addFooter(doc); y = 45; }
  y = addSectionTitle(doc, "6. High-Level Risks", y);
  const risks = (data.risks_summary as string[]) || [];
  risks.forEach((risk, i) => {
    doc.setFillColor(...COLORS.gold as [number,number,number]);
    doc.rect(15, y, 2, 4, "F");
    doc.setFontSize(8); doc.setFont("helvetica", "normal"); doc.setTextColor(...COLORS.textMid as [number,number,number]);
    doc.text(`${i + 1}. ${risk}`, 20, y + 3);
    y += 7;
  });
  y += 5;

  // Success criteria
  y = addSectionTitle(doc, "7. Success Criteria", y);
  const criteria = (data.success_criteria as string[]) || [];
  criteria.forEach((c, i) => {
    doc.setFillColor(...COLORS.success as [number,number,number]);
    doc.circle(18, y + 1.5, 1.5, "F");
    doc.setFontSize(8); doc.setFont("helvetica", "normal"); doc.setTextColor(...COLORS.textMid as [number,number,number]);
    doc.text(`${i + 1}. ${c}`, 22, y + 3);
    y += 7;
  });

  // Authorization box
  if (y > 220) { doc.addPage(); addHeader(doc, "Project Charter", `ميثاق المشروع — ${projectName}`, 4); addFooter(doc); y = 45; }
  y += 10;
  doc.setFillColor(...COLORS.bgLight as [number,number,number]);
  doc.setDrawColor(...COLORS.border as [number,number,number]);
  doc.roundedRect(15, y, W - 30, 30, 3, 3, "FD");
  doc.setFontSize(10); doc.setFont("helvetica", "bold"); doc.setTextColor(...COLORS.navy as [number,number,number]);
  doc.text("Authorization", 20, y + 8);
  doc.setFontSize(8); doc.setFont("helvetica", "normal"); doc.setTextColor(...COLORS.textMid as [number,number,number]);
  doc.text("Project Sponsor: _______________________________", 20, y + 18);
  doc.text("Project Manager: _______________________________", 20, y + 26);
  doc.text("Date: ____________", W / 2, y + 26);

  return doc.output("arraybuffer") as unknown as Uint8Array;
}

// ============================
// 2. Risk Register PDF
// ============================
export async function generateRiskRegisterPDF(data: Record<string, unknown>, projectName: string): Promise<Uint8Array> {
  const doc = createBasePDF();
  const W = doc.internal.pageSize.getWidth();
  let y = 45;

  addHeader(doc, "Risk Register", `سجل المخاطر — ${projectName}`);
  addFooter(doc);

  // Summary boxes
  const summary = data.summary as { total_risks: number; critical: number; high: number; medium: number; low: number; overall_risk_level: string } || {};
  const summBoxes = [
    { label: "Total Risks", value: String(summary.total_risks || 0) },
    { label: "Critical", value: String(summary.critical || 0) },
    { label: "High", value: String(summary.high || 0) },
    { label: "Medium", value: String(summary.medium || 0) },
    { label: "Low", value: String(summary.low || 0) },
  ];
  const bw = (W - 30) / 5;
  summBoxes.forEach((b, i) => addInfoBox(doc, b.label, b.value, 15 + i * (bw + 1), y, bw - 1, 18));
  y += 28;

  // Risk table
  const risks = (data.risks as Array<{
    id: string; risk_statement: string; category: string;
    probability_score: number; impact_score: number; risk_score: number;
    risk_level: string; response_strategy: string; response_actions: string[];
    contingency_plan: string; owner: string; status: string;
  }>) || [];

  autoTable(doc, {
    startY: y,
    head: [["ID", "Risk Statement", "Cat.", "P", "I", "Score", "Level", "Strategy", "Owner"]],
    body: risks.map(r => [
      r.id,
      r.risk_statement.substring(0, 60) + (r.risk_statement.length > 60 ? "..." : ""),
      r.category,
      r.probability_score,
      r.impact_score,
      r.risk_score,
      r.risk_level,
      r.response_strategy,
      r.owner,
    ]),
    styles: { font: "helvetica", fontSize: 7, cellPadding: 2 },
    headStyles: { fillColor: COLORS.navy as [number,number,number], textColor: 255, fontStyle: "bold", fontSize: 7 },
    alternateRowStyles: { fillColor: COLORS.bgLight as [number,number,number] },
    columnStyles: {
      0: { cellWidth: 12 }, 1: { cellWidth: 55 }, 2: { cellWidth: 16 },
      3: { cellWidth: 8, halign: "center" }, 4: { cellWidth: 8, halign: "center" },
      5: { cellWidth: 12, halign: "center" }, 6: { cellWidth: 16 },
      7: { cellWidth: 18 }, 8: { cellWidth: 20 },
    },
    didParseCell: (hookData) => {
      if (hookData.column.index === 5 && hookData.section === "body") {
        const score = Number(hookData.cell.raw);
        if (score >= 15) hookData.cell.styles.fillColor = [254, 202, 202];
        else if (score >= 8) hookData.cell.styles.fillColor = [254, 215, 170];
        else if (score >= 4) hookData.cell.styles.fillColor = [254, 249, 195];
        else hookData.cell.styles.fillColor = [167, 243, 208];
      }
    },
    margin: { left: 15, right: 15 },
  });

  return doc.output("arraybuffer") as unknown as Uint8Array;
}

// ============================
// 3. Generic Project Plan PDF
// ============================
export async function generateProjectPlanPDF(agendaData: Record<string, unknown>, projectName: string): Promise<Uint8Array> {
  const doc = createBasePDF();
  const W = doc.internal.pageSize.getWidth();
  let y = 45;
  let pageNum = 1;

  addHeader(doc, "Project Management Plan", `خطة إدارة المشروع — ${projectName}`, pageNum);
  addFooter(doc);

  // Overview
  y = addSectionTitle(doc, "1. Project Overview", y);
  doc.setFontSize(9); doc.setFont("helvetica", "normal"); doc.setTextColor(...COLORS.textMid as [number,number,number]);
  const overviewLines = doc.splitTextToSize((agendaData.project_overview as string) || "", W - 30);
  doc.text(overviewLines, 15, y);
  y += overviewLines.length * 5 + 5;

  // Methodology badge
  doc.setFillColor(...COLORS.primary as [number,number,number]);
  doc.roundedRect(15, y, 70, 10, 2, 2, "F");
  doc.setFontSize(8); doc.setFont("helvetica", "bold"); doc.setTextColor(255, 255, 255);
  doc.text(`Methodology: ${agendaData.methodology || "Predictive"}`, 50, y + 7, { align: "center" });

  doc.setFillColor(...COLORS.gold as [number,number,number]);
  doc.roundedRect(90, y, 70, 10, 2, 2, "F");
  doc.setTextColor(30, 30, 30);
  doc.text(`Est. Effort: ${agendaData.estimated_effort_hours || 0} hrs`, 125, y + 7, { align: "center" });
  y += 20;

  // Phases table
  y = addSectionTitle(doc, "2. Project Phases", y);
  const phases = (agendaData.phases as Array<{ name: string; start_week: number; end_week: number; description: string; deliverables: string[] }>) || [];
  autoTable(doc, {
    startY: y,
    head: [["Phase", "Start Wk", "End Wk", "Description", "Key Deliverables"]],
    body: phases.map(p => [
      p.name,
      `Wk ${p.start_week}`,
      `Wk ${p.end_week}`,
      p.description.substring(0, 50),
      (p.deliverables || []).slice(0, 2).join(", "),
    ]),
    styles: { font: "helvetica", fontSize: 8, cellPadding: 3 },
    headStyles: { fillColor: COLORS.navy as [number,number,number], textColor: 255, fontStyle: "bold" },
    alternateRowStyles: { fillColor: COLORS.bgLight as [number,number,number] },
    columnStyles: {
      0: { cellWidth: 30 }, 1: { cellWidth: 16, halign: "center" },
      2: { cellWidth: 16, halign: "center" }, 3: { cellWidth: 65 }, 4: { cellWidth: 50 },
    },
    margin: { left: 15, right: 15 },
  });
  y = (doc as any).lastAutoTable.finalY + 12;

  // New page for milestones & KPIs
  doc.addPage(); pageNum++;
  addHeader(doc, "Project Management Plan", `خطة إدارة المشروع — ${projectName}`, pageNum);
  addFooter(doc);
  y = 45;

  // Milestones
  y = addSectionTitle(doc, "3. Key Milestones", y);
  const milestones = (agendaData.key_milestones as Array<{ name: string; week: number; description: string; success_criteria: string }>) || [];
  autoTable(doc, {
    startY: y,
    head: [["Milestone", "Week", "Description", "Success Criteria"]],
    body: milestones.map(m => [m.name, `Wk ${m.week}`, m.description, m.success_criteria]),
    styles: { font: "helvetica", fontSize: 8, cellPadding: 3 },
    headStyles: { fillColor: COLORS.navy as [number,number,number], textColor: 255, fontStyle: "bold" },
    alternateRowStyles: { fillColor: COLORS.bgLight as [number,number,number] },
    columnStyles: { 0: { cellWidth: 40 }, 1: { cellWidth: 15, halign: "center" }, 2: { cellWidth: 60 }, 3: { cellWidth: 60 } },
    margin: { left: 15, right: 15 },
  });
  y = (doc as any).lastAutoTable.finalY + 12;

  // KPIs
  y = addSectionTitle(doc, "4. Key Performance Indicators (KPIs)", y);
  const kpis = (agendaData.kpis as Array<{ name: string; target: string; measurement_method: string; frequency: string }>) || [];
  autoTable(doc, {
    startY: y,
    head: [["KPI", "Target", "Measurement Method", "Frequency"]],
    body: kpis.map(k => [k.name, k.target, k.measurement_method, k.frequency]),
    styles: { font: "helvetica", fontSize: 8, cellPadding: 3 },
    headStyles: { fillColor: COLORS.success as [number,number,number], textColor: 255, fontStyle: "bold" },
    alternateRowStyles: { fillColor: [240, 253, 244] },
    margin: { left: 15, right: 15 },
  });

  return doc.output("arraybuffer") as unknown as Uint8Array;
}
